:cluster_name: #
  flighting_release: false
  flighting_preview: false
  doCleanup: True
  sub_vars: ../vars/agce_devops_sub_vars.yml
  workload_vars: #
  sp_appid: #
  sp_password: #

stages:
- stage: ${{parameters.stageName}}
  dependsOn: []    
  jobs:
  - job: deploy_notebook_steps
    displayName: ${{parameters.jobDisplayName}}

    pool:
      name: ${{parameters.Agent}}
      demands: ${{parameters.Demands}}
    container: "rocker/tidyverse:latest"

    timeoutInMinutes: ${{parameters.jobTimeoutInMinutes}}
  
    workspace:
      clean: all
  
    variables:
    - template: ${{parameters.sub_vars}}
    - template: ${{parameters.workload_vars}}
  
    steps:
    - template: ../steps/deploy_container_steps_v2.yml
      parameters:
        template: ${{variables.Template}}
        azureSubscription: ${{variables.azureSubscription}}
        azure_subscription: ${{variables.azure_subscription}}
        azureresourcegroup: ${{variables.TridentWorkloadTypeShort}}-${{variables.DeployLocation}}${{parameters.TestPostfix}}
        workspacename: ${{variables.TridentWorkloadTypeShort}}-${{variables.DeployLocation}}
        azureregion: ${{variables.DeployLocation}}
        aksimagename: ${{parameters.aksimagename}}
        aks_name: ${{variables.TridentWorkloadTypeShort}}${{parameters.TestPostfix}}
        location: ${{variables.ProjectLocation}}
        python_path: ${{parameters.DefaultWorkingDirectory}}${{variables.PythonPath}}
        cluster_name: ${{variables.TridentWorkloadTypeShort}}${{parameters.TestPostfix}}
        flighting_release: ${{parameters.flighting_release}}
        flighting_preview: ${{parameters.flighting_preview}}
        sp_appid: ${{parameters.sp_appid}}
        sp_password: ${{parameters.sp_password}}
        doCleanup: ${{parameters.doCleanup}}

  TridentWorkloadTypeShort: airmlrts
  DeployLocation: eastus
  ProjectLocation: ""
  PythonPath: .
  Template: RMLAKSDeployAMLJob.yml
